# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7Uv-COqYQPPyGJwY6WxA2w0YY4HIFYL
"""

pip install requests

import requests

# Define the URL of the Flask app
base_url = "http://localhost:5000"

def test_predict():
    response = requests.post(f"{base_url}/predict", data={
        "Area": "1000",
        "No_of_Bedrooms": "3",
        "Location": "JP Nagar Phase 1"
    })
    assert response.status_code == 200
    assert "Predicted Price" in response.text

if __name__ == "__main__":
    test_predict()
    print("Tests passed.")